### ISSUE TITLE
Replace grpc-web in frontend with connect-web for all code

### ISSUE THREAD

**Issue by meling** [quickfeed/quickfeed#840]
We currently use a mix of both connect-web and grpc-web in the frontend. We should ditch grpc-web. That would reduce the bundle size significantly; we can remove these two plugins:

```yaml
  - remote: buf.build/protocolbuffers/plugins/js:v3.20.1-1
    out: public/proto
    opt: import_style=commonjs,binary
  - remote: buf.build/grpc/plugins/web:v1.4.1-1
    out: public/proto
    opt:
      - import_style=typescript,
      - mode=grpcweb
```
